package com.footfisi.tienda.entity;
// Generated 16-feb-2020 9:02:08 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MantProductoTallaId generated by hbm2java
 */
@Embeddable
public class MantProductoTallaId implements java.io.Serializable {

	private int idProducto;
	private int idTalla;

	public MantProductoTallaId() {
	}

	public MantProductoTallaId(int idProducto, int idTalla) {
		this.idProducto = idProducto;
		this.idTalla = idTalla;
	}

	@Column(name = "\"id_Producto\"", nullable = false)
	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	@Column(name = "\"id_Talla\"", nullable = false)
	public int getIdTalla() {
		return this.idTalla;
	}

	public void setIdTalla(int idTalla) {
		this.idTalla = idTalla;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MantProductoTallaId))
			return false;
		MantProductoTallaId castOther = (MantProductoTallaId) other;

		return (this.getIdProducto() == castOther.getIdProducto()) && (this.getIdTalla() == castOther.getIdTalla());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProducto();
		result = 37 * result + this.getIdTalla();
		return result;
	}

}
