package com.footfisi.tienda.entity;
// Generated 09-feb-2020 20:45:28 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MantProductoTalla generated by hbm2java
 */
@Entity
@Table(name = "mant_talla", schema = "public")
public class MantTalla implements java.io.Serializable {

	private int idTalla;
	private String vdescripcion;
	private Set<MantProductoTalla> mantTallas = new HashSet<MantProductoTalla>(0);

	public MantTalla() {
	}

	public MantTalla(int idTalla) {
		this.idTalla = idTalla;
	}

	public MantTalla(int idTalla, String vdescripcion, Set<MantProductoTalla> mantTallas) {
		this.idTalla = idTalla;
		this.vdescripcion = vdescripcion;
		this.mantTallas = mantTallas;
	}

	@Id

	@Column(name = "id_talla", unique = true, nullable = false)
	public int getIdTalla() {
		return this.idTalla;
	}

	public void setIdTalla(int idTalla) {
		this.idTalla = idTalla;
	}

	@Column(name = "\"vDescripcion\"")
	public String getVdescripcion() {
		return this.vdescripcion;
	}

	public void setVdescripcion(String vdescripcion) {
		this.vdescripcion = vdescripcion;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantTalla")
	public Set<MantProductoTalla> getMantTallas() {
		return this.mantTallas;
	}

	public void setMantTallas(Set<MantProductoTalla> mantTallas) {
		this.mantTallas = mantTallas;
	}

}
