package com.footfisi.tienda.entity;
// Generated 09-feb-2020 20:45:28 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MantProducto generated by hbm2java
 */
@Entity
@Table(name = "mant_producto", schema = "public")
public class MantProducto implements java.io.Serializable {

	private int idProducto;
	private MantProductoCategoria mantProductoCategoria;
	private MantProductoTalla mantProductoTalla;
	private String vnombre;
	private String vdescripcion;
	private BigDecimal nprecioUnitario;
	private Integer ncantidad;
	private String vfoto;
	private Set<RegPedidoProducto> regPedidoProductos = new HashSet<RegPedidoProducto>(0);

	public MantProducto() {
	}

	public MantProducto(int idProducto, String vfoto) {
		this.idProducto = idProducto;
		this.vfoto = vfoto;
	}

	public MantProducto(int idProducto, MantProductoCategoria mantProductoCategoria,
			MantProductoTalla mantProductoTalla, String vnombre, String vdescripcion, BigDecimal nprecioUnitario,
			Integer ncantidad, String vfoto, Set<RegPedidoProducto> regPedidoProductos) {
		this.idProducto = idProducto;
		this.mantProductoCategoria = mantProductoCategoria;
		this.mantProductoTalla = mantProductoTalla;
		this.vnombre = vnombre;
		this.vdescripcion = vdescripcion;
		this.nprecioUnitario = nprecioUnitario;
		this.ncantidad = ncantidad;
		this.vfoto = vfoto;
		this.regPedidoProductos = regPedidoProductos;
	}

	@Id

	@Column(name = "id_producto", unique = true, nullable = false)
	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_categoria")
	public MantProductoCategoria getMantProductoCategoria() {
		return this.mantProductoCategoria;
	}

	public void setMantProductoCategoria(MantProductoCategoria mantProductoCategoria) {
		this.mantProductoCategoria = mantProductoCategoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_talla")
	public MantProductoTalla getMantProductoTalla() {
		return this.mantProductoTalla;
	}

	public void setMantProductoTalla(MantProductoTalla mantProductoTalla) {
		this.mantProductoTalla = mantProductoTalla;
	}

	@Column(name = "\"vNombre\"")
	public String getVnombre() {
		return this.vnombre;
	}

	public void setVnombre(String vnombre) {
		this.vnombre = vnombre;
	}

	@Column(name = "\"vDescripcion\"")
	public String getVdescripcion() {
		return this.vdescripcion;
	}

	public void setVdescripcion(String vdescripcion) {
		this.vdescripcion = vdescripcion;
	}

	@Column(name = "\"nPrecioUnitario\"", precision = 131089, scale = 0)
	public BigDecimal getNprecioUnitario() {
		return this.nprecioUnitario;
	}

	public void setNprecioUnitario(BigDecimal nprecioUnitario) {
		this.nprecioUnitario = nprecioUnitario;
	}

	@Column(name = "\"nCantidad\"")
	public Integer getNcantidad() {
		return this.ncantidad;
	}

	public void setNcantidad(Integer ncantidad) {
		this.ncantidad = ncantidad;
	}

	@Column(name = "\"vFoto\"", nullable = false)
	public String getVfoto() {
		return this.vfoto;
	}

	public void setVfoto(String vfoto) {
		this.vfoto = vfoto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantProducto")
	public Set<RegPedidoProducto> getRegPedidoProductos() {
		return this.regPedidoProductos;
	}

	public void setRegPedidoProductos(Set<RegPedidoProducto> regPedidoProductos) {
		this.regPedidoProductos = regPedidoProductos;
	}

}
