package com.footfisi.tienda.entity;
// Generated 09-feb-2020 20:45:28 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MantTipoDocumento generated by hbm2java
 */
@Entity
@Table(name = "mant_tipo_documento", schema = "public")
public class MantTipoDocumento implements java.io.Serializable {

	private String idTipoDocumento;
	private String vdescripcionLarga;
	private String vdescripcionCorta;
	private Set<RegPersona> regPersonas = new HashSet<RegPersona>(0);

	public MantTipoDocumento() {
	}

	public MantTipoDocumento(String idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	public MantTipoDocumento(String idTipoDocumento, String vdescripcionLarga, String vdescripcionCorta,
			Set<RegPersona> regPersonas) {
		this.idTipoDocumento = idTipoDocumento;
		this.vdescripcionLarga = vdescripcionLarga;
		this.vdescripcionCorta = vdescripcionCorta;
		this.regPersonas = regPersonas;
	}

	@Id

	@Column(name = "id_tipo_documento", unique = true, nullable = false)
	public String getIdTipoDocumento() {
		return this.idTipoDocumento;
	}

	public void setIdTipoDocumento(String idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	@Column(name = "\"vDescripcionLarga\"")
	public String getVdescripcionLarga() {
		return this.vdescripcionLarga;
	}

	public void setVdescripcionLarga(String vdescripcionLarga) {
		this.vdescripcionLarga = vdescripcionLarga;
	}

	@Column(name = "\"vDescripcionCorta\"")
	public String getVdescripcionCorta() {
		return this.vdescripcionCorta;
	}

	public void setVdescripcionCorta(String vdescripcionCorta) {
		this.vdescripcionCorta = vdescripcionCorta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantTipoDocumento")
	public Set<RegPersona> getRegPersonas() {
		return this.regPersonas;
	}

	public void setRegPersonas(Set<RegPersona> regPersonas) {
		this.regPersonas = regPersonas;
	}

}
