package com.footfisi.tienda.entity;
// Generated 09-feb-2020 20:45:28 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MantProductoCategoria generated by hbm2java
 */
@Entity
@Table(name = "mant_producto_categoria", schema = "public")
public class MantProductoCategoria implements java.io.Serializable {

	private int idCategoria;
	private String vmarca;
	private String vgenero;
	private String vtipo;
	private Set<MantProducto> mantProductos = new HashSet<MantProducto>(0);

	public MantProductoCategoria() {
	}

	public MantProductoCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	public MantProductoCategoria(int idCategoria, String vmarca, String vgenero, String vtipo, Set<MantProducto> mantProductos) {
		this.idCategoria = idCategoria;
		this.vmarca = vmarca;
		this.vgenero = vgenero;
		this.vtipo = vtipo;
		this.mantProductos = mantProductos;
	}

	@Id

	@Column(name = "id_categoria", unique = true, nullable = false)
	public int getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	@Column(name = "\"vMarca\"")
	public String getVmarca() {
		return this.vmarca;
	}

	public void setVmarca(String vmarca) {
		this.vmarca = vmarca;
	}

	@Column(name = "\"vGenero\"")
	public String getVgenero() {
		return this.vgenero;
	}

	public void setVgenero(String vgenero) {
		this.vgenero = vgenero;
	}

	@Column(name = "\"vTipo\"")
	public String getVtipo() {
		return this.vtipo;
	}

	public void setVtipo(String vtipo) {
		this.vtipo = vtipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantProductoCategoria")
	public Set<MantProducto> getMantProductos() {
		return this.mantProductos;
	}

	public void setMantProductos(Set<MantProducto> mantProductos) {
		this.mantProductos = mantProductos;
	}

}
