package com.footfisi.tienda.entity;
// Generated 16-feb-2020 9:02:08 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MantProductoTalla generated by hbm2java
 */
@Entity
@Table(name = "mant_producto_talla", schema = "public")
public class MantProductoTalla implements java.io.Serializable {

	private MantProductoTallaId id;
	private MantProducto mantProducto;
	private MantTalla mantTalla;

	public MantProductoTalla() {
	}

	public MantProductoTalla(MantProductoTallaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idProducto", column = @Column(name = "\"id_Producto\"", nullable = false)),
			@AttributeOverride(name = "idTalla", column = @Column(name = "\"id_Talla\"", nullable = false)) })
	public MantProductoTallaId getId() {
		return this.id;
	}

	public void setId(MantProductoTallaId id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"id_Talla\"", nullable = false, insertable = false, updatable = false)
	public MantTalla getMantTalla() {
		return this.mantTalla;
	}

	public void setMantTalla(MantTalla mantTalla) {
		this.mantTalla = mantTalla;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"id_Producto\"", nullable = false, insertable = false, updatable = false)
	public MantProducto getMantProducto() {
		return mantProducto;
	}

	public void setMantProducto(MantProducto mantProducto) {
		this.mantProducto = mantProducto;
	}

}
