package com.footfisi.tienda.entity;
// Generated 09-feb-2020 20:45:28 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegComprobante generated by hbm2java
 */
@Entity
@Table(name = "reg_comprobante", schema = "public")
public class RegComprobante implements java.io.Serializable {

	private int idComprobante;
	private String vtipoComprobante;
	private Date dfecha;
	private String vestado;
	private Set<RegPedido> regPedidos = new HashSet<RegPedido>(0);

	public RegComprobante() {
	}

	public RegComprobante(int idComprobante) {
		this.idComprobante = idComprobante;
	}

	public RegComprobante(int idComprobante, String vtipoComprobante, Date dfecha, String vestado, Set<RegPedido> regPedidos) {
		this.idComprobante = idComprobante;
		this.vtipoComprobante = vtipoComprobante;
		this.dfecha = dfecha;
		this.vestado = vestado;
		this.regPedidos = regPedidos;
	}

	@Id

	@Column(name = "id_comprobante", unique = true, nullable = false)
	public int getIdComprobante() {
		return this.idComprobante;
	}

	public void setIdComprobante(int idComprobante) {
		this.idComprobante = idComprobante;
	}

	@Column(name = "\"vTipoComprobante\"")
	public String getVtipoComprobante() {
		return this.vtipoComprobante;
	}

	public void setVtipoComprobante(String vtipoComprobante) {
		this.vtipoComprobante = vtipoComprobante;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "\"dFecha\"", length = 13)
	public Date getDfecha() {
		return this.dfecha;
	}

	public void setDfecha(Date dfecha) {
		this.dfecha = dfecha;
	}

	@Column(name = "\"vEstado\"")
	public String getVestado() {
		return this.vestado;
	}

	public void setVestado(String vestado) {
		this.vestado = vestado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regComprobante")
	public Set<RegPedido> getRegPedidos() {
		return this.regPedidos;
	}

	public void setRegPedidos(Set<RegPedido> regPedidos) {
		this.regPedidos = regPedidos;
	}

}
