package com.footfisi.tienda.entity;
// Generated 09-feb-2020 20:45:28 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegPedido generated by hbm2java
 */
@Entity
@Table(name = "reg_pedido", schema = "public")
public class RegPedido implements java.io.Serializable {

	private int idPedido;
	private RegCliente regCliente;
	private RegComprobante regComprobante;
	private RegTrabajador regTrabajador;
	private BigDecimal nprecioTotal;
	private Date dfechaCompra;
	private Date dfechaPago;
	private String vestado;
	private Set<RegPedidoProducto> regPedidoProductos = new HashSet<RegPedidoProducto>(0);

	public RegPedido() {
	}

	public RegPedido(int idPedido, RegCliente regCliente) {
		this.idPedido = idPedido;
		this.regCliente = regCliente;
	}

	public RegPedido(int idPedido, RegCliente regCliente, RegComprobante regComprobante, RegTrabajador regTrabajador,
			BigDecimal nprecioTotal, Date dfechaCompra, Date dfechaPago, String vestado, Set<RegPedidoProducto> regPedidoProductos) {
		this.idPedido = idPedido;
		this.regCliente = regCliente;
		this.regComprobante = regComprobante;
		this.regTrabajador = regTrabajador;
		this.nprecioTotal = nprecioTotal;
		this.dfechaCompra = dfechaCompra;
		this.dfechaPago = dfechaPago;
		this.vestado = vestado;
		this.regPedidoProductos = regPedidoProductos;
	}

	@Id

	@Column(name = "id_pedido", unique = true, nullable = false)
	public int getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(int idPedido) {
		this.idPedido = idPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "\"vTipoDocumentoCliente\"", referencedColumnName = "id_tipo_documento", nullable = false),
			@JoinColumn(name = "\"vNumeroDocumentoCliente\"", referencedColumnName = "\"vNumeroDocumento\"", nullable = false)
			})
	public RegCliente getRegCliente() {
		return this.regCliente;
	}

	public void setRegCliente(RegCliente regCliente) {
		this.regCliente = regCliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_comprobante")
	public RegComprobante getRegComprobante() {
		return this.regComprobante;
	}

	public void setRegComprobante(RegComprobante regComprobante) {
		this.regComprobante = regComprobante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "\"vTipoDocumentoTrabajador\"", referencedColumnName = "id_tipo_documento"),
			@JoinColumn(name = "\"vNumeroDocumentoTrabajador\"", referencedColumnName = "\"vNumeroDocumento\"") })
	public RegTrabajador getRegTrabajador() {
		return this.regTrabajador;
	}

	public void setRegTrabajador(RegTrabajador regTrabajador) {
		this.regTrabajador = regTrabajador;
	}

	@Column(name = "\"nPrecioTotal\"", precision = 131089, scale = 0)
	public BigDecimal getNprecioTotal() {
		return this.nprecioTotal;
	}

	public void setNprecioTotal(BigDecimal nprecioTotal) {
		this.nprecioTotal = nprecioTotal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "\"dFechaCompra\"", length = 13)
	public Date getDfechaCompra() {
		return this.dfechaCompra;
	}

	public void setDfechaCompra(Date dfechaCompra) {
		this.dfechaCompra = dfechaCompra;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "\"dFechaPago\"", length = 13)
	public Date getDfechaPago() {
		return this.dfechaPago;
	}

	public void setDfechaPago(Date dfechaPago) {
		this.dfechaPago = dfechaPago;
	}

	@Column(name = "\"vEstado\"")
	public String getVestado() {
		return this.vestado;
	}

	public void setVestado(String vestado) {
		this.vestado = vestado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regPedido")
	public Set<RegPedidoProducto> getRegPedidoProductos() {
		return this.regPedidoProductos;
	}

	public void setRegPedidoProductos(Set<RegPedidoProducto> regPedidoProductos) {
		this.regPedidoProductos = regPedidoProductos;
	}

}
