package com.footfisi.tienda.entity;
// Generated 09-feb-2020 20:45:28 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegPersonaId generated by hbm2java
 */
@Embeddable
public class RegPersonaId implements java.io.Serializable {

	private String idTipoDocumento;
	private String vnumeroDocumento;

	public RegPersonaId() {
	}

	public RegPersonaId(String idTipoDocumento, String vnumeroDocumento) {
		this.idTipoDocumento = idTipoDocumento;
		this.vnumeroDocumento = vnumeroDocumento;
	}

	@Column(name = "id_tipo_documento", nullable = false)
	public String getIdTipoDocumento() {
		return this.idTipoDocumento;
	}

	public void setIdTipoDocumento(String idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	@Column(name = "\"vNumeroDocumento\"", nullable = false)
	public String getVnumeroDocumento() {
		return this.vnumeroDocumento;
	}

	public void setVnumeroDocumento(String vnumeroDocumento) {
		this.vnumeroDocumento = vnumeroDocumento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegPersonaId))
			return false;
		RegPersonaId castOther = (RegPersonaId) other;

		return ((this.getIdTipoDocumento() == castOther.getIdTipoDocumento())
				|| (this.getIdTipoDocumento() != null && castOther.getIdTipoDocumento() != null
						&& this.getIdTipoDocumento().equals(castOther.getIdTipoDocumento())))
				&& ((this.getVnumeroDocumento() == castOther.getVnumeroDocumento())
						|| (this.getVnumeroDocumento() != null && castOther.getVnumeroDocumento() != null
								&& this.getVnumeroDocumento().equals(castOther.getVnumeroDocumento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdTipoDocumento() == null ? 0 : this.getIdTipoDocumento().hashCode());
		result = 37 * result + (getVnumeroDocumento() == null ? 0 : this.getVnumeroDocumento().hashCode());
		return result;
	}

}
