package com.footfisi.tienda.entity;
// Generated 09-feb-2020 20:45:28 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RegPersona generated by hbm2java
 */
@Entity
@Table(name = "reg_persona", schema = "public")
public class RegPersona implements java.io.Serializable {

	private RegPersonaId id;
	private MantTipoDocumento mantTipoDocumento;
	private String vapellidoPaterno;
	private String vapellidoMaterno;
	private String vnombres;
	private Set<SegUsuario> segUsuarios = new HashSet<SegUsuario>(0);

	public RegPersona() {
	}

	public RegPersona(RegPersonaId id, MantTipoDocumento mantTipoDocumento) {
		this.id = id;
		this.mantTipoDocumento = mantTipoDocumento;
	}

	public RegPersona(RegPersonaId id, MantTipoDocumento mantTipoDocumento, String vapellidoPaterno,
			String vapellidoMaterno, String vnombres, Set<SegUsuario> segUsuarios) {
		this.id = id;
		this.mantTipoDocumento = mantTipoDocumento;
		this.vapellidoPaterno = vapellidoPaterno;
		this.vapellidoMaterno = vapellidoMaterno;
		this.vnombres = vnombres;
		this.segUsuarios = segUsuarios;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idTipoDocumento", column = @Column(name = "id_tipo_documento", nullable = false)),
			@AttributeOverride(name = "vnumeroDocumento", column = @Column(name = "\"vNumeroDocumento\"", nullable = false)) })
	public RegPersonaId getId() {
		return this.id;
	}

	public void setId(RegPersonaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_documento", nullable = false, insertable = false, updatable = false)
	public MantTipoDocumento getMantTipoDocumento() {
		return this.mantTipoDocumento;
	}

	public void setMantTipoDocumento(MantTipoDocumento mantTipoDocumento) {
		this.mantTipoDocumento = mantTipoDocumento;
	}

	@Column(name = "\"vApellidoPaterno\"")
	public String getVapellidoPaterno() {
		return this.vapellidoPaterno;
	}

	public void setVapellidoPaterno(String vapellidoPaterno) {
		this.vapellidoPaterno = vapellidoPaterno;
	}

	@Column(name = "\"vApellidoMaterno\"")
	public String getVapellidoMaterno() {
		return this.vapellidoMaterno;
	}

	public void setVapellidoMaterno(String vapellidoMaterno) {
		this.vapellidoMaterno = vapellidoMaterno;
	}

	@Column(name = "\"vNombres\"")
	public String getVnombres() {
		return this.vnombres;
	}

	public void setVnombres(String vnombres) {
		this.vnombres = vnombres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regPersona")
	public Set<SegUsuario> getSegUsuarios() {
		return this.segUsuarios;
	}

	public void setSegUsuarios(Set<SegUsuario> segUsuarios) {
		this.segUsuarios = segUsuarios;
	}

}
