package com.footfisi.tienda.entity;
// Generated 09-feb-2020 20:45:28 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegPedidoProductoId generated by hbm2java
 */
@Embeddable
public class RegPedidoProductoId implements java.io.Serializable {

	private int idPedido;
	private int idProducto;

	public RegPedidoProductoId() {
	}

	public RegPedidoProductoId(int idPedido, int idProducto) {
		this.idPedido = idPedido;
		this.idProducto = idProducto;
	}

	@Column(name = "\"id_Pedido\"", nullable = false)
	public int getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(int idPedido) {
		this.idPedido = idPedido;
	}

	@Column(name = "\"id_Producto\"", nullable = false)
	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegPedidoProductoId))
			return false;
		RegPedidoProductoId castOther = (RegPedidoProductoId) other;

		return (this.getIdPedido() == castOther.getIdPedido()) && (this.getIdProducto() == castOther.getIdProducto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPedido();
		result = 37 * result + this.getIdProducto();
		return result;
	}

}
