package com.footfisi.tienda.entity;
// Generated 09-feb-2020 20:45:28 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SegUsuario generated by hbm2java
 */
@Entity
@Table(name = "seg_usuario", schema = "public")
public class SegUsuario implements java.io.Serializable {

	private String idUsuario;
	private RegPersona regPersona;
	private String vcontrasenia;

	public SegUsuario() {
	}

	public SegUsuario(String idUsuario, RegPersona regPersona) {
		this.idUsuario = idUsuario;
		this.regPersona = regPersona;
	}

	public SegUsuario(String idUsuario, RegPersona regPersona, String vcontrasenia) {
		this.idUsuario = idUsuario;
		this.regPersona = regPersona;
		this.vcontrasenia = vcontrasenia;
	}

	@Id

	@Column(name = "id_usuario", unique = true, nullable = false)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "id_tipo_documento", referencedColumnName = "id_tipo_documento", nullable = false),
			@JoinColumn(name = "\"vNumeroDocumento\"", referencedColumnName = "\"vNumeroDocumento\"", nullable = false) })
	public RegPersona getRegPersona() {
		return this.regPersona;
	}

	public void setRegPersona(RegPersona regPersona) {
		this.regPersona = regPersona;
	}

	@Column(name = "\"vContrasenia\"")
	public String getVcontrasenia() {
		return this.vcontrasenia;
	}

	public void setVcontrasenia(String vcontrasenia) {
		this.vcontrasenia = vcontrasenia;
	}

}
